In [1]:
import numpy as nb

In [7]:
# creating array with arange function of numpy
a=nb.arange(15)
a=nb.arange(15).reshape(3,5)

In [8]:
# size of array
a.size

15

In [9]:
# dimensions of array
a.ndim

2

In [10]:
# datatype of array
a.dtype

dtype('int32')

In [11]:
# shape of array
a.shape

(3, 5)

In [12]:
# creating array from a iteration
list_b = [1,2,3,4,5,6,7,8,9]
b=nb.array(list_b).reshape(3,3)

In [ ]:
# creating multi-dimension array from a iteration
b=nb.array([(1.5,2,3),(4,5,6)])

In [42]:
# dtype can also be specified
c=nb.array([[1,2],[3,4]], dtype=complex)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [15]:
# array of zeros
zeros=nb.zeros((3,4))

In [17]:
# array of ones
ones=nb.ones((2,3,4), dtype=nb.int16)

In [18]:
# custom range
cd = nb.arange(0,2,0.3)

In [19]:
# getting the required number of elements
nb.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
a = nb.array([20,30,40,50])
b = nb.arange(4)      #array([0,1,2,3])
c = a-b  # output : array([20,29,38,47])

In [37]:
b**2        #output : array([0,1,4,9])
10*nb.sin(a) #output : [ 9.12945251, -9.88031624,  7.4511316,  -2.62374854]
a<35    #output : array([True, True, False, False])

array([ True,  True, False, False])

In [40]:
A=nb.array([[1,1],[0,1]])
B=nb.array([[2,0],[3,4]])

prod1 = A*B          # elementwise product
prod2 = A@B          # matrix product
prod2 = A.dot(B)     # another matrix product

In [43]:
a = nb.ones((2,3), dtype=int)
b = nb.random.random((2,3))
a*=3        # multiplies to each elements
b+=3        # adds to each elements

In [44]:
a = nb.random.random((2,3))
print(a)
# output : array

a.sum()

a.min()

a.max()

[[0.49111197 0.29764634 0.01457433]
 [0.17195885 0.53077824 0.581165  ]]


0.5811650045692597