In [2]:
import numpy as nb

In [3]:
# creating array with arange function of numpy
a=nb.arange(15)
a=nb.arange(15).reshape(3,5)

In [4]:
# size of array
a.size

15

In [5]:
# dimensions of array
a.ndim

2

In [6]:
# datatype of array
a.dtype

dtype('int32')

In [7]:
# shape of array
a.shape

(3, 5)

In [8]:
# creating array from a iteration
list_b = [1,2,3,4,5,6,7,8,9]
b=nb.array(list_b).reshape(3,3)

In [9]:
# creating multi-dimension array from a iteration
b=nb.array([(1.5,2,3),(4,5,6)])

In [10]:
# dtype can also be specified
c=nb.array([[1,2],[3,4]], dtype=complex)

In [11]:
# array of zeros
zeros=nb.zeros((3,4))

In [12]:
# array of ones
ones=nb.ones((2,3,4), dtype=nb.int16)

In [13]:
# custom range
cd = nb.arange(0,2,0.3)

In [14]:
# getting the required number of elements
nb.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
a = nb.array([20,30,40,50])
b = nb.arange(4)      #array([0,1,2,3])
c = a-b  # output : array([20,29,38,47])

In [16]:
b**2        #output : array([0,1,4,9])
10*nb.sin(a) #output : [ 9.12945251, -9.88031624,  7.4511316,  -2.62374854]
a<35    #output : array([True, True, False, False])

array([ True,  True, False, False])

In [17]:
A=nb.array([[1,1],[0,1]])
B=nb.array([[2,0],[3,4]])

prod1 = A*B          # elementwise product
prod2 = A@B          # matrix product
prod2 = A.dot(B)     # another matrix product

In [18]:
a = nb.ones((2,3), dtype=int)
b = nb.random.random((2,3))
a*=3        # multiplies to each elements
b+=3        # adds to each elements

In [19]:
a = nb.random.random((2,3))
print(a)
# output : array

a.sum()

a.min()

a.max()

[[0.39698353 0.68102402 0.10073609]
 [0.72440043 0.78763089 0.20506145]]


0.7876308856492611

In [20]:
rand_arr=nb.random.randint(1,10,(4,5))
print(rand_arr)

[[3 8 6 6 6]
 [2 1 5 7 9]
 [8 4 3 1 1]
 [2 3 1 5 4]]


In [21]:
rand_arr.sum()

85

In [22]:
rand_arr.max()

9

In [23]:
rand_arr.min()

1

In [26]:
nb.random.random( (4,5) )*100

array([[94.34186861, 51.76492744, 33.38783663, 33.5962138 , 61.37956238],
       [75.6458551 , 30.11645592, 20.13469909, 17.17295054, 74.30992866],
       [63.79383304, 86.30812067, 33.05130958, 36.19954395, 29.38541294],
       [94.74989088, 54.91688693, 54.30629253, 95.01423955, 85.85483576]])

In [28]:
arr1 = nb.arange(11,20).reshape(3,3)

In [32]:
arr1[1,2]

16

In [33]:
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [34]:
arr2 =nb.arange(1,21).reshape(4,5)

In [35]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
arr2[3,3]

19

In [38]:
arr2[2,3:5]

array([14, 15])

In [40]:
arr2[1:4,1]

array([ 7, 12, 17])

In [44]:
arr2.diagonal()

array([ 1,  7, 13, 19])